spring:
  application:
    name: spring-with-openapi
  security:
    user:
      name: admin
      password: secret
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: shutdown
      base-path: /admin/actuator


resilience4j:
  ratelimiter:
    instances:
      apiRateLimiter:
        limit-for-period: 5
        limit-refresh-period: 10s
        timeout-duration: 0
  circuitbreaker:
    instances:
      apiCircuitBreaker:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: count_based
        sliding-window-size: 10