global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'outbox-service'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          __metrics_path__: /actuator/prometheus

